const data = {
    products: [
      {
        _id: '1',
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: '/images/sam.jpg',
        price: 120,
        countInStock:10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Men\'s suit',
        category: 'Shirts',
        image: '/images/blazer1.jpeg',
        price: 100,
        countInStock:20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Track Suit',
        category: 'Pants',
        image: '/images/pants2.jpeg',
        price: 220,
        countInStock:0,
        brand: 'Nike',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/pants1.jpg',
        price: 78,
        countInStock:15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Canvas',
        category: 'Shoes',
        image: '/images/shoe1.jpg',
        price: 65,
        countInStock:5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Women\'s Suit',
        category: 'Suit',
        image: '/images/blazer2.jpeg',
        price: 139,
        countInStock:12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;